export interface User {
  id: string;
  name: string;
  email: string;
  password?: string;
  accessCFO: boolean;
  accessSoldado: boolean;
  isAdmin: boolean;
  isApproved: boolean;
  createdAt: string;
  lastLoginAt?: string;
  previousLoginAt?: string;
  plan?: "mensal" | "trimestral" | "indefinido";
  planEndDate?: string;
}

export interface CycleSubject {
  id: string;
  name: string;
  completed: boolean;
}

export interface CycleDay {
  dayNumber: number; // 1 to 7
  questionTarget: number;
  questionSolved: number;
  subjects: CycleSubject[]; // up to 4
  completed: boolean;
  notes?: string; // Observações do dia
}

export interface StudyCycle {
  id: string;
  studentId: string;
  studentName: string;
  weekNumber: number;
  days: CycleDay[];
  unlockedAt: string; // Date string
  isCompleted: boolean;
  cycleDetails?: string; // Detalhes do ciclo, plano de estudos por período
}

export interface PerformanceLog {
  id: string;
  studentId: string;
  date: string;
  subject: string;
  topic: string;
  reasonForError: string; // Motivo do erro
  questionsAttempted: number;
  questionsCorrect: number;
}

export interface ContentItem {
  id: string;
  title: string;
  subtitle: string;
  type: "video" | "pdf" | "link" | "simulado";
  url: string; // YouTube video link or external URL
  category: "cfo" | "soldado" | "both";
  createdAt: string;
  topic?: string; // Tópico
  subtopic?: string; // Subtópico
  contentMarkdown?: string; // Rich markdown text generated by Tenente IA
  additionalPdfs?: { name: string; url: string }[];
}

export interface WeeklyReport {
  id: string;
  studentId: string;
  weekNumber: number;
  content: string; // Markdown / Text report
  createdAt: string;
  updatedAt: string;
}

export interface SyllabusItem {
  id: string;
  title: string;
  isCompleted: boolean;
  studyCount: number; // For tracking revision loop
  hasSummary: boolean;
  hasQuestions: boolean;
  correctRate: number; // percentage (0-100)
  spacedRepetitionActive?: boolean;
  nextRevisionDate?: string;
  revisionStage?: number;
  lastRevisionDate?: string;
  isRevision?: boolean;
  revisionType?: "questoes" | "flashcards";
}

export interface SyllabusSection {
  id: string;
  category: "cfo" | "soldado";
  subject: string; // e.g. "LÍNGUA PORTUGUESA", "DIREITO CONSTITUCIONAL"
  topics: SyllabusItem[];
}

export interface CoordQuestion {
  id: string;
  statement: string;
  options: string[]; // Options list (4 or 5)
  correctOptionIndex: number; // 0-indexed correct answer
  explanation: string; // Detailed resolution explanation
  createdAt: string;
  subject: string; // Subject tag
  topic?: string; // Topic / Assunto específico (e.g. "Crase", "Artigo 5º")
  difficulty?: "Fácil" | "Média" | "Difícil"; // Difficulty tag
  year?: string; // Question year (e.g. "2026")
  banca?: string; // Examination board (e.g. "IBFC")
}

export interface PasswordResetRequest {
  id: string;
  email: string;
  name: string;
  status: "pending" | "completed";
  createdAt: string;
}

export interface EssaySubmission {
  id: string;
  studentId: string;
  studentName: string;
  studentEmail: string;
  theme: string;
  submissionType: "typed" | "image";
  essayText: string;
  imageUrl?: string;
  createdAt: string;
  status: "pending" | "corrected";
  score?: number;
  correctionFeedback?: string;
  correctionDetails?: {
    themeAndStructureScore: number; // Max 20
    cohesionCoherenceScore: number; // Max 25
    informativeArgumentativeScore: number; // Max 25
    grammarFormalNormScore: number; // Max 30
    overallScore: number; // Max 100
    themeFeedback: string;
    cohesionFeedback: string;
    argumentationFeedback: string;
    grammarFeedback: string;
    rewrittenText: string;

    // PMBA 5 Competencies (each 0 to 20 points, sum 100)
    grammarScore?: number;
    structureScore?: number;
    contentScore?: number;
    cohesionScore?: number;
    argumentationScore?: number;

    // Feedback for 5 competencies
    grammarFeedbackText?: string;
    structureFeedbackText?: string;
    contentFeedbackText?: string;
    cohesionFeedbackText?: string;
    argumentationFeedbackText?: string;
  };
}

export interface EssayTheme {
  id: string;
  title: string;
  motivatingText?: string;
  category?: "soldado" | "cfo" | "geral";
  createdAt: string;
}

export interface StudyModule {
  id: string;
  name: string;
  description?: string;
  createdAt: string;
}

